---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8ssandra-io-v1alpha1-k8ssandracluster
  failurePolicy: Fail
  name: vk8ssandracluster.kb.io
  rules:
  - apiGroups:
    - k8ssandra.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - k8ssandraclusters
  sideEffects: None
