# permissions for end users to edit cassandrabackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cassandrabackup-editor-role
rules:
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - cassandrabackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - cassandrabackups/status
  verbs:
  - get
