# permissions for end users to view cassandrabackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cassandrabackup-viewer-role
rules:
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - cassandrabackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - medusa.k8ssandra.io
  resources:
  - cassandrabackups/status
  verbs:
  - get
