# permissions for end users to view k8ssandraclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8ssandracluster-viewer-role
rules:
- apiGroups:
  - k8ssandra.io
  resources:
  - k8ssandraclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8ssandra.io
  resources:
  - k8ssandraclusters/status
  verbs:
  - get
