# permissions for end users to view replicatedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicatedsecret-viewer-role
rules:
- apiGroups:
  - replication.k8ssandra.io
  resources:
  - replicatedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replication.k8ssandra.io
  resources:
  - replicatedsecrets/status
  verbs:
  - get
