# permissions for end users to edit replicatedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicatedsecret-editor-role
rules:
- apiGroups:
  - replication.k8ssandra.io
  resources:
  - replicatedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.k8ssandra.io
  resources:
  - replicatedsecrets/status
  verbs:
  - get
