apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8ssandra-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8ssandra-operator
subjects:
- kind: ServiceAccount
  name: k8ssandra-operator
#  namespace: system
