# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: k8ssandraclusters.k8ssandra.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: system
          name: k8ssandra-operator-webhook-service
          path: /convert
      conversionReviewVersions:
      - v1
