// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScheduling) DeepCopyInto(out *AutoScheduling) {
	*out = *in
	if in.ExcludedKeyspaces != nil {
		in, out := &in.ExcludedKeyspaces, &out.ExcludedKeyspaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScheduling.
func (in *AutoScheduling) DeepCopy() *AutoScheduling {
	if in == nil {
		return nil
	}
	out := new(AutoScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraReaper) DeepCopyInto(out *CassandraReaper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraReaper.
func (in *CassandraReaper) DeepCopy() *CassandraReaper {
	if in == nil {
		return nil
	}
	out := new(CassandraReaper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CassandraReaper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraReaperList) DeepCopyInto(out *CassandraReaperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CassandraReaper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraReaperList.
func (in *CassandraReaperList) DeepCopy() *CassandraReaperList {
	if in == nil {
		return nil
	}
	out := new(CassandraReaperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CassandraReaperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraReaperSpec) DeepCopyInto(out *CassandraReaperSpec) {
	*out = *in
	in.ServerConfig.DeepCopyInto(&out.ServerConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraReaperSpec.
func (in *CassandraReaperSpec) DeepCopy() *CassandraReaperSpec {
	if in == nil {
		return nil
	}
	out := new(CassandraReaperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraReaperStatus) DeepCopyInto(out *CassandraReaperStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraReaperStatus.
func (in *CassandraReaperStatus) DeepCopy() *CassandraReaperStatus {
	if in == nil {
		return nil
	}
	out := new(CassandraReaperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfig) DeepCopyInto(out *ServerConfig) {
	*out = *in
	in.AutoScheduling.DeepCopyInto(&out.AutoScheduling)
	if in.HangingRepairTimeoutMins != nil {
		in, out := &in.HangingRepairTimeoutMins, &out.HangingRepairTimeoutMins
		*out = new(int32)
		**out = **in
	}
	if in.RepairRunThreadCount != nil {
		in, out := &in.RepairRunThreadCount, &out.RepairRunThreadCount
		*out = new(int32)
		**out = **in
	}
	if in.ScheduleDaysBetween != nil {
		in, out := &in.ScheduleDaysBetween, &out.ScheduleDaysBetween
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfig.
func (in *ServerConfig) DeepCopy() *ServerConfig {
	if in == nil {
		return nil
	}
	out := new(ServerConfig)
	in.DeepCopyInto(out)
	return out
}
