apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - patches/manager_auth_proxy_patch.yaml

resources:
- rbac/auth_proxy_service.yaml
- rbac/auth_proxy_role.yaml
- rbac/auth_proxy_role_binding.yaml
- rbac/auth_proxy_client_clusterrole.yaml

